# This task gets all Junos configuration from all devices
- name: Build and deploy configuration
  hosts: vqfx10k
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Build configuration
      template: src=vqfx.conf.j2 dest=/tmp/{{ inventory_hostname }}.conf
    - name: Deploy config to device ... please wait
      juniper_junos_config:
        load: 'override'
        src: "/tmp/{{ inventory_hostname }}.conf"
        host: "{{ ansible_ssh_host }}"
        port: "{{ ansible_ssh_port }}"
        user: root
        passwd: Juniper
        format: text
        logfile: /tmp/changes.log
